import { StudentType } from "@/apiRequest/students"

export const INITIAL_SLOTS: StudentType[] = [
  {
    id: 0,
    nickname: "???",
    avatar: { id: "", url: "" },
    uid: "",
    code: "",
    isCheckIn: true,
    fullName: "",
    gender: false,
    parentPhone: "",
    point: { extraPoint: 0, minusPoint: 0 },
    group: "",
  },
  {
    id: 1,
    nickname: "???",
    avatar: { id: "", url: "" },
    uid: "",
    code: "",
    isCheckIn: true,
    fullName: "",
    gender: false,
    parentPhone: "",
    point: { extraPoint: 0, minusPoint: 0 },
    group: "",
  },
  {
    id: 2,
    nickname: "???",
    avatar: { id: "", url: "" },
    uid: "",
    code: "",
    isCheckIn: true,
    fullName: "",
    gender: false,
    parentPhone: "",
    point: { extraPoint: 0, minusPoint: 0 },
    group: "",
  },
  {
    id: 3,
    nickname: "???",
    avatar: { id: "", url: "" },
    uid: "",
    code: "",
    isCheckIn: true,
    fullName: "",
    gender: false,
    parentPhone: "",
    point: { extraPoint: 0, minusPoint: 0 },
    group: "",
  },
]
